import Link from "next/link";
import "./globals.css";
import HeaderMenu from "@/components/HeaderMenu";
import { AuthProvider } from "@/hooks/useAuth";
// import { Inter } from "next/font/google";
// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <div className="flex flex-col min-h-screen">
            <header className="bg-gray-800 text-white p-4">
              <div className="container mx-auto">
                <nav className="flex items-center justify-between">
                  <div className="text-xl font-bold">
                    <Link href="/">Next.js Demo</Link>
                  </div>
                  <HeaderMenu />
                </nav>
              </div>
            </header>

            <main className="flex-1 container mx-auto py-8 px-4">
              {children}
            </main>

            <footer className="bg-gray-800 text-white p-4">
              <div className="container mx-auto text-center">
                &copy; {new Date().getFullYear()} Your Company. All rights
                reserved.
              </div>
            </footer>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
