import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="flex flex-col min-h-screen">
          <header className="bg-gray-800 text-white p-4">
            <div className="container mx-auto">
              <nav className="flex items-center justify-between">
                <div className="text-xl font-bold">Next.js Demo</div>
                <ul className="flex space-x-4">
                  <li>
                    <Link href="/" className="hover:text-gray-300">
                      Home
                    </Link>
                  </li>
                  <li>
                    <Link href="/teacher" className="hover:text-gray-300">
                      Teachers
                    </Link>
                  </li>
                  <li>
                    <Link href="/student" className="hover:text-gray-300">
                      Students
                    </Link>
                  </li>
                  <li>
                    <Link href="/todo" className="hover:text-gray-300">
                      To do
                    </Link>
                  </li>
                  <li>
                    <Link href="/user/login" className="hover:text-gray-300">
                      Login
                    </Link>
                  </li>
                  <li>
                    <Link href="/user/signup" className="hover:text-gray-300">
                      Sign up
                    </Link>
                  </li>
                </ul>
              </nav>
            </div>
          </header>

          <main className="flex-1 container mx-auto py-8 px-4">{children}</main>

          <footer className="bg-gray-800 text-white p-4">
            <div className="container mx-auto text-center">
              &copy; {new Date().getFullYear()} Your Company. All rights
              reserved.
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
